app:
  version: "1.0.0"
  port: "80"
  mode: "production"
  log_level: "info"

goff:
  endpoint: "http://relay:1031"
  environment: "production"

keycloak:
  url: "https://auth.bettercity.app/"
  realm: "bettercity"
  client_id: "better-feature-flag"
  client_secret: env://KEYCLOAK_CLIENT_SECRET

jwt:
  secret: ""

